language: node_js

sudo: false

node_js:
    - '10'
    - 'lts/*'
    - 'node'

matrix:
    fast_finish: true

before_install:
    - export CHROME_BIN=chromium-browser

services:
    - xvfb

install:
    - npm ci

script: 'npm run travis'

after_success:
    - npm run coveralls
