# From: https://github.com/GoogleChrome/puppeteer/blob/master/.travis.yml
language: node_js

addons:
    apt:
        packages:
            # This is required to run new chrome on old trusty
            - libnss3

sudo: false

node_js:
    - "8"
    - "lts/*"
    - "node"

# allow headful tests
before_install:
    # Enable user namespace cloning
    - "sysctl kernel.unprivileged_userns_clone=1"
    # Launch XVFB
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - npm ci

script: "npm test"

matrix:
    fast_finish: true
