language: node_js

addons:
    apt:
        packages:
            - libnss3

sudo: false

node_js:
    - '8'
    - 'lts/*'
    - 'node'

matrix:
    fast_finish: true

before_install:
    - 'sysctl kernel.unprivileged_userns_clone=1'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'

install:
    - npm ci

script: 'npm run travis'

after_success:
    - npm run coveralls
